### PR TITLE
Add a daemonize_child function to Daemonize, which leaves the parent …

### PR DESCRIPTION
**Pull request by aweinstock314**
…alive.

### CODE REVIEW

**Comment by knsd** [comment]
Hello, Avi. Can you please describe this pull request if it's still relevant.

**Comment by aweinstock314** [comment]
It's still relevant.

`daemonize_child` is a generalization of `start` that allows the caller to continue on in both the parent and the child. This allows (among other things) a library to spawn a daemon without aborting it's caller.

The concrete use case I had in mind was for better clipboard support under x11. Here's a link to the main discussion of the issues: https://mozilla.logbot.info/servo/20150803#c250006-c250123. The precautions I was taking to try to daemonize were less thorough than what this library provides, caussing issues like https://mozilla.logbot.info/servo/20151009#c279844-c279848.

**Comment by aweinstock314** [comment]
I agree with the changes to replace i32 with libc::pid_t, and have pushed that to the PR branch. I also added Clone/Debug impls for ForkResult.

As far as the parent getting a reference to the intermediate pid, it's the simplest implementation. I wrote ForkResult to preserve the pid in order to be as thin a wrapper around fork as possible (while still being type-safe).
 That the parent gets the intermediate pid (rather than the final pid) is due to the need for the parent to return from the first fork (before the cwd/umask are changed), not the second, so the second pid isn't in scope.

Which of the following approaches would you prefer for the intermediate pid?
1) Leave it as is, with the simple implementation.
2) Change ForkResult to be polymorphic over the parent return type as well as the child return type, and return Ok(Parent(())) from daemonize_child.
3) Do some pipe(2)-ish communication to return the daemon's pid, rather than the intermediate pid.

I don't think there's a harm to leaving the pid in (as in option 1), but if you think there is, option 2 is a simple fix to hide that information from the caller.                                                                Option 3 adds complexity and performance overhead, but might be more semantically meaningful.

**Comment by knsd** [comment]
I think option 1 can be confusing for library users. I really love option 3 and this option will fix #15 instantly, but it can be difficult to implement correctly.

**Pull request closed without merging**
